//! Resolves locked versions from `poetry.lock`.

use std::fs;

use tower_lsp::lsp_types::Url;
use tracing::warn;

use crate::parser::types::RegistryType;
use crate::version::error::LockError;
use crate::version::lock::{LockResolver, extract_package_version_from_toml_lock, find_lock_file};

const LOCK_FILE_NAME: &str = "poetry.lock";

pub struct PoetryLockResolver;

impl LockResolver for PoetryLockResolver {
    fn registry_type(&self) -> RegistryType {
        RegistryType::PyPI
    }

    fn resolve_locked_version(
        &self,
        manifest_uri: &Url,
        package_name: &str,
    ) -> Result<Option<String>, LockError> {
        let Some(lock_path) = find_lock_file(manifest_uri, LOCK_FILE_NAME)? else {
            return Ok(None);
        };

        let content = fs::read_to_string(&lock_path)
            .inspect_err(|e| warn!("Failed to read {:?}: {}", lock_path, e))?;

        Ok(extract_package_version_from_toml_lock(
            &content,
            package_name,
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    const POETRY_LOCK_SAMPLE: &str = r#"# This file is automatically @generated by Poetry 1.7.0 and should not be changed by hand.

[[package]]
name = "click"
version = "8.1.7"
description = "Composable command line interface toolkit"
optional = false
python-versions = ">=3.7"

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"

[metadata]
lock-version = "2.0"
"#;

    #[test]
    fn resolves_version_from_poetry_lock() {
        let tmp = TempDir::new().unwrap();
        let manifest = tmp.path().join("pyproject.toml");
        fs::write(&manifest, "").unwrap();
        fs::write(tmp.path().join(LOCK_FILE_NAME), POETRY_LOCK_SAMPLE).unwrap();

        let uri = Url::from_file_path(&manifest).unwrap();
        let result = PoetryLockResolver
            .resolve_locked_version(&uri, "requests")
            .unwrap();

        assert_eq!(result, Some("2.31.0".to_string()));
    }

    #[test]
    fn returns_none_for_unknown_package() {
        let tmp = TempDir::new().unwrap();
        let manifest = tmp.path().join("pyproject.toml");
        fs::write(&manifest, "").unwrap();
        fs::write(tmp.path().join(LOCK_FILE_NAME), POETRY_LOCK_SAMPLE).unwrap();

        let uri = Url::from_file_path(&manifest).unwrap();
        let result = PoetryLockResolver
            .resolve_locked_version(&uri, "django")
            .unwrap();

        assert_eq!(result, None);
    }
}
