//! Resolves locked versions from `yarn.lock` (yarn classic v1 and Berry v2+).

use std::fs;

use tower_lsp::lsp_types::Url;
use tracing::warn;

use crate::parser::types::RegistryType;
use crate::version::error::LockError;
use crate::version::lock::{LockResolver, find_lock_file};

const LOCK_FILE_NAME: &str = "yarn.lock";

pub struct YarnLockResolver;

impl LockResolver for YarnLockResolver {
    fn registry_type(&self) -> RegistryType {
        RegistryType::Npm
    }

    fn resolve_locked_version(
        &self,
        manifest_uri: &Url,
        package_name: &str,
    ) -> Result<Option<String>, LockError> {
        let Some(lock_path) = find_lock_file(manifest_uri, LOCK_FILE_NAME)? else {
            return Ok(None);
        };

        let content = fs::read_to_string(&lock_path)
            .inspect_err(|e| warn!("Failed to read {:?}: {}", lock_path, e))?;

        Ok(extract_locked_version(&content, package_name))
    }
}

/// Walk yarn.lock entries (top-level `<key>:` lines, indented body).
/// Returns the version of the first entry whose key spec matches `package_name`.
/// Handles both v1 (`version "X"`) and Berry (`version: X`) syntax and peer-dep
/// suffixes (`18.2.0_react@npm:18.2.0` → `18.2.0`).
fn extract_locked_version(content: &str, package_name: &str) -> Option<String> {
    let mut in_matching_entry = false;
    let mut current_version: Option<String> = None;

    for raw_line in content.lines() {
        if raw_line.is_empty() || raw_line.starts_with('#') {
            continue;
        }

        let is_top_level = !raw_line.starts_with(char::is_whitespace);

        if is_top_level {
            if in_matching_entry && current_version.is_some() {
                return current_version;
            }
            // Skip Berry's `__metadata:` block and similar non-package keys.
            if raw_line.starts_with("__") {
                in_matching_entry = false;
                continue;
            }
            in_matching_entry = key_matches_package(raw_line, package_name);
            current_version = None;
            continue;
        }

        if !in_matching_entry || current_version.is_some() {
            continue;
        }

        let trimmed = raw_line.trim_start();
        if let Some(value) = parse_version_field(trimmed) {
            current_version = Some(strip_peer_suffix(&value).to_string());
        }
    }

    current_version
}

/// `version "X"` (v1) or `version: X` (Berry). Returns the unquoted value.
fn parse_version_field(line: &str) -> Option<String> {
    if let Some(rest) = line.strip_prefix("version ") {
        return rest
            .trim()
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .map(str::to_string);
    }
    if let Some(rest) = line.strip_prefix("version:") {
        let value = rest.trim().trim_matches('"');
        if value.is_empty() {
            return None;
        }
        return Some(value.to_string());
    }
    None
}

/// A key line like `"react@^17.0.0", "react@~17.0.2":` matches `react`.
/// Multi-spec keys are split on `,` and each spec checked independently.
fn key_matches_package(line: &str, package_name: &str) -> bool {
    let key = line.trim_end_matches(':');
    key.split(',').any(|spec| {
        let spec = spec.trim().trim_matches('"');
        spec_name(spec)
            .map(|name| name == package_name)
            .unwrap_or(false)
    })
}

/// Extract the package name from a yarn key spec.
/// `@types/node@npm:^20.0.0` → `@types/node`; `lodash@^4.17.0` → `lodash`.
fn spec_name(spec: &str) -> Option<&str> {
    let (offset, search) = if let Some(rest) = spec.strip_prefix('@') {
        (1, rest)
    } else {
        (0, spec)
    };
    let at = search.find('@')?;
    Some(&spec[..offset + at])
}

fn strip_peer_suffix(version: &str) -> &str {
    match version.find('_') {
        Some(idx) => &version[..idx],
        None => version,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const V1_SAMPLE: &str = r#"# THIS IS AN AUTOGENERATED FILE.

# yarn lockfile v1


"@types/node@^20.0.0":
  version "20.10.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.10.0.tgz"
  integrity sha512-fake

"react@^18.0.0", "react@~18.2.0":
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
"#;

    const BERRY_SAMPLE: &str = r#"# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 6
  cacheKey: 8

"@types/node@npm:^20.0.0":
  version: 20.10.0
  resolution: "@types/node@npm:20.10.0"
  checksum: fake

"react-dom@npm:^18.0.0":
  version: 18.2.0
  resolution: "react-dom@npm:18.2.0"

"react@npm:^18.0.0":
  version: 18.2.0_react-dom@18.2.0
  resolution: "react@npm:18.2.0"
"#;

    #[test]
    fn v1_resolves_unscoped_package() {
        assert_eq!(
            extract_locked_version(V1_SAMPLE, "lodash"),
            Some("4.17.21".to_string())
        );
    }

    #[test]
    fn v1_resolves_scoped_package() {
        assert_eq!(
            extract_locked_version(V1_SAMPLE, "@types/node"),
            Some("20.10.0".to_string())
        );
    }

    #[test]
    fn v1_resolves_multi_spec_entry() {
        assert_eq!(
            extract_locked_version(V1_SAMPLE, "react"),
            Some("18.2.0".to_string())
        );
    }

    #[test]
    fn berry_resolves_scoped_package() {
        assert_eq!(
            extract_locked_version(BERRY_SAMPLE, "@types/node"),
            Some("20.10.0".to_string())
        );
    }

    #[test]
    fn berry_skips_metadata_block() {
        // __metadata's `version: 6` must not be returned for any package lookup.
        assert_eq!(extract_locked_version(BERRY_SAMPLE, "__metadata"), None);
    }

    #[test]
    fn berry_strips_peer_suffix() {
        assert_eq!(
            extract_locked_version(BERRY_SAMPLE, "react"),
            Some("18.2.0".to_string())
        );
    }

    #[test]
    fn returns_none_for_unknown_package() {
        assert_eq!(extract_locked_version(V1_SAMPLE, "vue"), None);
    }
}
