name: Security audit

on:
  schedule:
    - cron: "0 0 */3 * *"

  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install cargo-audit
        uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b # v2.83.4
        with:
          tool: cargo-audit

      - name: Run audit
        run: cargo audit
