name: Security audit

on:
  schedule:
    - cron: "0 0 */3 * *"

  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install cargo-audit
        uses: taiki-e/install-action@91ddec75689c4c78665b598d188dc821c5a43e5c # v2.85.9
        with:
          tool: cargo-audit

      - name: Run audit
        run: cargo audit
